[theme]
primaryColor = "#FF69B4"  # A soft pink for interactive elements
backgroundColor = "#000000"  # Deep black for the main background
secondaryBackgroundColor = "#2E2E2E"  # Warm gray for widgets and sidebar
textColor = "#FFFFFF"  # White for text readability
font = "cursive"  # Elegant cursive font for headings